sudo: required
dist: trusty
language: node_js
node_js:
- '6'
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=eyevinntechnology/channelengine
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- if [ ! -z "$TRAVIS_TAG" ]; then docker push $REPO ; fi
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: zVxqazGOR3WGJrl8rLAtACRYD/baKTzRx/O6OwTNu8JeVQIp+1Vd01m5LQEBIE/L2m1WRaJG+75FzZM3sejUnya+lsDXHYlfBCH3dbduE1LXeTapZvbpFuUqYfw7MpVzr/gJ940voWdCGeu1bk7+eg/Ktl4RX9srnAE2IbBsh96SuTcrqbTj4O3rIakJs/0XNYTsEHnaewwVNRaN1pQJb8l0AUUb1z1Bo2lVvw0AYJJL3Jd53wYO8ZAGrzgqcTMLJmpa5XEK1FTJ1vO+D8T7ueyQqLrcr2DtyDJ1S8mjUMfyPxI8fxrIY7mSwQk6kyaek+seSpeZnHN+p6auf6c45WaWD6QP4T/OmrvM7ESBEKz8ZFVSnbYy920U4PhIGUUMoMAGzXa5g1PLKvTWOQfbTxwIwA6PKeVLbuu0ntDuPfzxvU7ASHKyorCm/QCM1yacFtU6AM5DYhc/F0q//b13WoknY6+9h/tmluL4IieTMG4SrdwwtxY9h3an0le5nsqLCjshzVDqXjLLdWG/N4jSexqOYzsTDH2iSUbx62DWSqIKUt4lBZTow5rIBYpS9bPD9dpumTnGZGq3IP1yN+X9SJry/EJ1qifKp6zfpuz3jrBCu+Y/kw20Miw6bXY4ZolKqchCV3AE1sJ8ke0BhZoP/w7j0dZRf/0ygRj1KTML5Ng=
  on:
    tags: true
    repo: Eyevinn/channel-engine
env:
  global:
  - secure: ao9PaafvY1p8uIqUvpX3VTSN4o8VQY1AaOllKgc8OxEH6RS0UtMPjleuREwThdWNMfotQFW0ynfubh3/HYAMmkaNyAsBheS+obBzqiHwRb0vmzWYnYVRD6zZKUyWzQml4ZLGiIVGZHnW+7uQ2F+TX9/mkuRQc+W7URw+EZkGu2p2hL4eKHqUlQitA9nzAPnp7zmOB54dxBlVsunm/ESOhEga/GfA/QwooaaXzKSxfQggNmx/AJzKplcIDMVcJ2+V8deuic+u2iIvZV5jS9BYXAThKtFx0pGlK7N3lv1Cc3WnTD4hNlf3a3SBhlUjSl6SPWUY2EjYOfgLNSU5kuaDDxul3FG9DU0b7kCIQ0kPLWLpj7+JK3yns8tm9FY6WVKtD/CvyfrEe83viPeOeo9bYUvzIRjOQ65hJzTwOq5Ymfg6rys6EsvsC7ykPUr75LECPmz8m14k3Z5LxcCcqvrDD5iFhYAhqayJwAnOWnKPn3bTzc3RuV7V9lEmlpr3XoUQyOXsk38Tm5Z7jqlAap6iJJLhyCuArB5U40iqqmOeOUsEGCQSuoxYMRQBQyYBhhl7Gms2wd/zy/PXkrfEBaaTK4WQlgAewlQbRo/q80DaWyvLPHh51kwsgBIi2G95rzf2dCAXCqJV01Wi7zV2/CgFdinGaDPTRtG9lJpXo4jhkWM=
  - secure: aAoKw81kq0whdv44J8hmMCIDMQwexNXWbpSMZ6TADv7eL2PmK4C113O7bAPV7c/iPscPkIaow6ZtgIUS4mywxf6u/loem7aml6b/EdUfk22AAB6+FaTiKlqBwwIgT8Gg8Fex7Sw1B8WhS1hlE3OpvE6r6/9uLwHwkvCyG7sh/I9fLGmQgAdq5WXRRVWVPD1my77cnZCMQOwxca7BQRYDlKi82OXMqsHBn5T4q4fp08NuzYmIYqbT6JDLui+cmLLvLuBgvJUqFq7tQPWI81xSqhp6ALPnbVOrZy0Sg8MwC2YrqwDyrWOzi3W5PvRKZ75/7ZfEjOocsX+9rNyo/YvQ0nvp9okc2Hvk/4gLDfm/j25jEz3oGy9klk4SqbhNLEL1nzyTA5HFau9vwrXBkW++NToojZp3+aAvUSkPI2RtpfkPWBwcy/Hv0Lq4OMBq4lGWfvoZXAyWiGwKKNOZ1JO2Uijji2gUrYT7GZBZzBcrEFBuonZC3G/CU30Dj1GpKMsyb1vkHzc7e6iGtPbQ4EwD7CIlAhL7T2ZjLyLOnbVN2WqlDTvdCKG/vEGW7cnx2QW5ZSJWI7bbFyBtvGVjVCJCY+1bORN00wy9eJpwCZIPpo90dx+5h5c3Z51GcDaDL6fF9XQx7cvWz47EMyVpyJg4dlBRB9OJjCj75LaB9YexDFk=
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: E7OPHwExwi5TBSBbpS6rrONyW/dXlirxDX8h7gQ8v7PVXoJBR+cVf4HsvRH97jNu3VzG3eiAkVcImY2yBlBFSKL1E2ESXjnDjvXiiZ4twWpthsYTe+ZEYy1Aqisa3TOXWcPOwlusowmQMyYx6WIfeC1RQEWnhZhh7DetVGE5GrCej9y4I+nq8JsL8mMZb3ljoruJ84EjBXDqyZ6+J3xtWuSQobw7YqjulRlO0alvp1pnUak606Cf10CLWtv3qIbWZjcJpLNxg0CfXEp/Blpz6MVJq3RbcU/8XVMKdSPIpyEcPFNRK4vxcphTPlfD7eLoh1g3n83cW2G6KtyYK/Fc/2hc0N8bNkIwT3F+Es3fGTqLhjIaDspKeek2cifF0dE63Q1TPkY1lWiNNK1ujzoLs1vOOnSi5jXkSIaVFvtnD/gUfyLEov+uixct8Cqd4Qd6J+r+jd9XgfsQNbuXuku++kv5Sc5LrJCvHsm/lJ6gAqQSFv4ycSaP0j3wguCdJOQLqjBAKYwDnbQdW9K+hjKcab+Pm1tJiQe3P3E6Aug6Nfe/gA2OUjGoWg2VycEbaW/80PAmI5FgAqlQ56V8rBrxcFASBTDNxieqAiJ4QHhzmPIdGotj0uYpTLt/XM50LI9Tdpb4M/reDU9kBQ3tEG2oPAdg3SX+vLN4ScztzYJvDQo=
